### ISSUE TITLE
Here I occur an error

### ISSUE THREAD

**Issue by anonymou3** [deb0ch/emacs-winum#3]
I use emacs in windows 7 and use emacsclient.

http://emacsbinw64.sourceforge.net/ Here is the emacs I am using.

The below line is my desktop shortcut :
emacs-w64-25.1-O2-with-modules\bin\emacsclientw.exe -na "" -c

Then I run this link, *Messages* buffer show:
Error during redisplay: (eval (winum-get-number-string)) signaled (wrong-type-argument stringp nil) [3 times]

If I run emacs-w64-25.1-O2-with-modules\bin\runemacs.exe here is no error occurred.

**Comment by deb0ch** [comment]
Hi, thanks for reporting !

I'm not a windows user, so I will need to take some time to get one and reproduce.

Can you please provide a minimal configuration to reproduce ? A file as small as possible that when you launch emacs with `emacs -Q -q your-file.el` you can reproduce the bug.

Also, are you using the latest version of `winum` available on GitHub or Melpa ?

I have a fix ready to push that should work for this, but I think it's important to understand the root cause :smile_cat:
 
I hope it's not totally blocking your Emacs ? If so tell me and I'll push right away.

**Comment by deb0ch** [comment]
More importantly, I couldn't find any documentation about a `-na ""` option, and my Emacs does not recognize it.

Do you know what it does and why it's here ? Could you please provide me a link to somewhere it is documented, if you know one ?

**Comment by anonymou3** [comment]
@deb0ch http://emacsbinw64.sourceforge.net/ is the windows version emacs that I used. Could you paste your fix code here then I can test quickly. Thank you @deb0ch !

**Comment by deb0ch** [comment]
Just wanted to know why you used the `-na ""` option and what it was doing, if you had any idea.

Just pushed a possible fix to github, you can apply the latest commit yourself (apply the patch or just copy the winum.el file that you see on github) or wait a few hours that Melpa has built the new release :smile_cat:

**Comment by anonymou3** [comment]
@deb0ch https://www.emacswiki.org/emacs/EmacsClient#toc4, 
I read the wiki here for Windows about the `-na ""` option. Now all thing is work fine. 
Thank you again for your help.

**Comment by deb0ch** [comment]
You're welcome, thanks for the link ! :+1::sparkles:
